### ISSUE TITLE
Unintended Overrides after mwe2 workflow 

### ISSUE THREAD

**Issue by Babwenbiber** [LorenzoBettini/jbase#113]
When I create my Classes with the mwe2 Workflow, in src-gen/...services/...GrammarAccess.java I have multiple Overrides which are probably not intended.
Example: 
```
	//@Override
	//QualifiedName:
	//    ValidID (=>'.' ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
        }
```
There are about 20-30 methods that have this overrides and actually have nothing to override in the parent class.
The program works anyways, but I get errors from the compiler (Not a supported specification statement keyword: "Override")

How can I fix that?
You can check configurations in [my repo](https://github.com/Babwenbiber/CorC)

**Comment by LorenzoBettini** [comment]
Could you please point me to the actual workflow?

**Comment by Babwenbiber** [comment]
Yes, sorry.
https://github.com/Babwenbiber/CorC/blob/master/de.tu_bs.cs.isf.cbc.textual.tool/src/de/tu_bs/cs/isf/cbc/textual/tool/GenerateDsl.mwe2

**Comment by LorenzoBettini** [comment]
mh... Jbase is not used here... are you sure you didn't report the issue on the wrong GitHub repository?

**Comment by Babwenbiber** [comment]
Sorry, forgot to push and just did a commit.
Its online now.

If You want to build it, don't get distracted from the errors in the other projects. I am just testing something.

**Comment by LorenzoBettini** [comment]
I cannot build the whole project, if you need help you should provide some more help, which version of Jbase are you using, which version of Xtext? The objectweb.asm version range is rather old in your MANIFEST

**Comment by Babwenbiber** [comment]
I reverted some commits for you in develop. [Here is a working version](https://github.com/Babwenbiber/CorC/tree/develop/de.tu-bs.cs.isf.taxonomy.model)
And here are my plugin versions.
![Bildschirmfoto 2021-06-21 um 09 20 59](https://user-images.githubusercontent.com/15171332/122722446-0829e480-d272-11eb-88a5-7c63fc41851e.png)

Let me know if you need more infos.

**Comment by LorenzoBettini** [comment]
so it's working now?

**Comment by Babwenbiber** [comment]
Like I said:
There are about 20-30 methods that have this overrides and actually have nothing to override in the parent class.
The program works anyways, but I get errors from the compiler (Not a supported specification statement keyword: "Override")
But I can execute the code

**Comment by szarnekow** [comment]
```java
	//@Override
	//QualifiedName:
	//    ValidID (=>'.' ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
        }
```
You do realize that this `@Override` is commented with a line comment, right?
What exact problem do you have?

**Comment by Babwenbiber** [comment]
I See that it is commented and still I get an error from the compiler

**Comment by LorenzoBettini** [comment]
Indeed I thought you had commented it out yourself to avoid the error from the compiler, but as @szarnekow says it's commented out so how can you get an error from the compiler?

**Comment by Babwenbiber** [comment]
I don't know. I just realized, that it is not a base but xtext problem (at least with my configuration).
I checkedout a fresh example (simple arithmetic) from Xtext and after mwe2 I get the same error (but it is only 1 Override not 20-30).
I can't figure out why the compiler is complaining.
![Bildschirmfoto 2021-06-21 um 13 47 37](https://user-images.githubusercontent.com/15171332/122757512-007d3680-d298-11eb-803b-cc7af5629fe9.png)
![Bildschirmfoto 2021-06-21 um 13 49 00](https://user-images.githubusercontent.com/15171332/122757519-0246fa00-d298-11eb-9b9f-63516d62fa79.png)
When I hover over it:
Multiple markers at this line
	- : Not a supported specification statement keyword: 
	 "Override"
	- Not a supported specification statement keyword: 
	 "Override"

**Comment by LorenzoBettini** [comment]
The error is generated by "jmlediting" I see... Is it that project https://www.key-project.org/eclipse/JMLEditing/ ?

**Comment by Babwenbiber** [comment]
Ah yes, that makes sense.
Thanks a lot. I will close this issue!
