### ISSUE TITLE
Support for Xtext 2.12

### ISSUE THREAD

**Issue by Babwenbiber** [LorenzoBettini/jbase#121]
Hi,
for some reasons I had to downgrade to Xtext 2.12.
Is there still support for 2.12?
On the update site I could only find jbase 0.0.9 which is for Xtext 2.15.

Cheers

**Comment by LorenzoBettini** [comment]
Sorry, no: that's too old and it would be too much work for me to support such an old version.
I strongly suggest you to update to a much more up to date version
