### ISSUE TITLE
Are Java bitwise operators possible here?

### ISSUE THREAD

**Issue by tommyettinger** [LorenzoBettini/jbase#46]
I realize Xtend seems to frown on bitwise-heavy code, but jbase seems to have Java compatibility as a goal, and that sometimes needs to include bitwise operators. There's relatively-obvious cases like treating 32-bit ints as unsigned by doing `-1 & 0xFFFFFFFFL` to get a long with the correct unsigned value. There's the common use case of `hashCode` implementations using xor. Then there's laughably obscure cases like

```
        System.out.println(new char[]{
                '$' << (',' ^ '-'), 
                '`' | ('-' - '('), 
                '$' << (',' ^ '-') | '$', 
                '$' << (',' ^ '-') | '$', 
                '/' + '@', 
                ',', 
                ' ', 
                '(' + '/', 
                '/' + '@', 
                '(' + '%' + '%', 
                '$' << (',' ^ '-') | '$', 
                '*' + ':', 
                '!'});
```

Which prints `Hello, World!` (without any alphanumeric chars in the text to print) using bitwise ops on `char` literals, something Java allows for some reason. Xbase doesn't define any bitwise operators or even static methods for byte or short values, which is a strange omission (nor does it define them for chars, but that's reasonable). I'm interested in the idea of producing an "augmented Java" that could read in normal Java and the augmented dialect with the same compiler/IDE plugin, and Jbase seems like an excellent way to get started with this. Is there any chance of seeing bitwise operators in Jbase, or am I mistaken in assuming they aren't there based on my quick read of the .xtext grammar?

**Comment by LorenzoBettini** [comment]
@tommyettinger sorry, I forgot about bitwise operators... I'll try to work on that this week.

**Comment by LorenzoBettini** [comment]
I've just released version 0.3.1 with bitwise operators

**Comment by tommyettinger** [comment]
Wow, that was a very quick release! I was going to post that `>>=` and the other shift-and-assign things were missing, but then I realized that they aren't missing at all, I just didn't see them. (The xtext file uses the convention of individual chars in sequence spelled out separately, though I don't know why. That makes a search for ">>=" not find that operator, but it's with the other operators, so I did find it eventually.).

So now I'm wondering...

Is there a simple way to extend the group of valid operators in a grammar that extends Jbase using `with jbase.Jbase`? I'm curious about using a single point of syntactic extension that makes it plain where the augmentations to Java are. Probably it would be like Clojure's "reader dispatch macro" character, `#`, which just means it changes the way the next section of code is read. In Clojure, `#"\w+"` is a specialized tweak to strings for regular expressions and produces code similar to `java.util.regex.Pattern.compile("\\w+")`. There's other uses for `#` as well over there, like the syntax for anonymous functions is `#(+ %1 %1 %2)` and that would return something like `long _anonymous(long _1, long _2){return _1 + _1 + _2;}` (except it would also work for any numerical type Clojure knows about). Both `""` and `()` mean something completely different without the `#`, though, so that's where I wonder about some sort of prefix differentiation marker, and "is it actually an operator"... I realize it's not a good fit for this issue, but do you have an idea about how I might approach this?

**Comment by LorenzoBettini** [comment]
@tommyettinger adding new operators should be easy: you need to redefine the datatype rule that is used in the super grammar, see, for example, https://github.com/LorenzoBettini/jbase/blob/master/jbase/src/jbase/Jbase.xtext and the datatype rule OpMultiAssign that adds &=, |= and ^=, then you need to have a Java class that defines the corresponding Java expression and some annotations, in a static method, see, for example, https://github.com/LorenzoBettini/jbase/blob/master/jbase.lib/src/jbase/lib/JbaseBooleanExtensions.java and then you need to bind your own OperatorMapping that maps the operator to the method name in your Java class, see for example, https://github.com/LorenzoBettini/jbase/blob/master/jbase/src/jbase/scoping/featurecalls/JbaseOperatorMapping.java the everything should work out of the box.

However, in your example, you don't want to define a new binary/unary operator, is that right?

**Comment by tommyettinger** [comment]
I wasn't initially sure, but yes that's right. A single point of extension probably wouldn't be an operator in the normal sense. I've been thinking about this, and I think there's only a few things I really would like to have in a language that Java doesn't quite do currently. Some of them are already in XBase or XTend: extension methods are very useful in the common case of consuming a 3rd-party library but wanting your own additions to it, short ways to produce lambda-like anonymous inner classes on target JDK versions less than Java 8 are important to me, and operator overloading (possibly for new operators using a limited symbol set) is currently part of and, in my opinion, should be part of most languages that add to Java. Some of the features I want aren't adequately supplied by XBase/XTend. There should be a way for user-defined data structures to have a short constructor that assigns values in the constructor (in a strongly-typed manner; I already have functions that can do this, though with almost no type-checking and not in a very concise way, on Map constructors, but it's possible for the compiler to ensure a Map<K, V> constructor is given alternating K and V arguments). I think there should be some kind of better approach to the simple cases of macros (possibly even as simple as word/phrase/regex substitution, as long as the replacement has a stable type that the compiler can check in the IDE) than the massive and heavyweight approach of active annotations. The last one might slip too much into the category of term-rewriting instead of macros, and could need restrictions to avoid infinite-replacement-loop issues if the replacement, for instance, was part-way written and replaced "term1" with "(term1 + term1)" (it's even the same type signature, as long as what addition returns is the same type as its operands). I think the last problem could be solved by always using macros by their name, never replacing unrelated code in a simple textual manner (though macros should be able to take arguments, which would be considered related code and be next to the name), having all macro names be out-of-scope or non-generated in the Java code, and having a macro's name not be visible within its own body (preventing macro recursion, and in a roundabout way also preventing mutual macro recursion).

The reason I'm mentioning this here is because I like the syntax JBase uses more than XBase/XTend's syntax (and I agree with the reasonable choice to use Java's behavior where a feature exists instead of inventing something new, like unrequested implicit List-to-array conversion). I think I'm a long way off from actually implementing this, especially since I've disabled the IntelliJ XText plugins since they were interfering with debugging in all projects, and not just XText ones. I also want to have some kind of standard library ready near the start of language development (starting in Java, but if the plan holds up I should be able to switch to using an extension of JBase).

Thanks for getting back to me on this, by the way. I'll keep these resources in mind when I start implementing.
