### ISSUE TITLE
[ERROR] ERROR:+ cannot be resolved (Maven)

### ISSUE THREAD

**Issue by camilo040494** [LorenzoBettini/jbase#71]
I have some problems when deploying the language execution with Maven, this is, the language is complete and everything can be seen in the [repository](https://github.com/unicesi/eketal), where it has everything working with Xtext and Jbase. The language is correctly built and his grammar his finished, so it can be install via maven. Once this is built, the grammar can be use to generate files to a project, the repository has some [examples](https://github.com/unicesi/eketal/tree/master/test) explaining how to use the grammar in some test’s. Everything can be built via Maven. But, inside the syntax, when writing java code on the file of the language (.eketal) and deployed with "mvn compile" (for example) in the test’s that use the language for generating code, the execute does not recognize the operators ‘+’, ’-’, ‘*’, ‘/’. For example (the reactions are the components in the grammar that uses jbase):
```
reaction before automatonConstructor.firstState{
		System.out.println("estado");
}
```
This code belongs to the [Hello World example](https://github.com/unicesi/eketal/blob/master/test/Hello-World/src/main/java/core/Example.eketal) in the test folder
That reaction when executing 'mvn compile' will run and generate all the classes as desire. But If you put any line that has a operation with those characters, like:
```
reaction before automatonConstructor.firstState{
        int x = 3+1;
	System.out.println("estado");
}
```
A maven exception is thrown saying: [ERROR] ERROR:+ cannot be resolved.
For the other side, if you take that line off, the maven execution will perform its operation as desire, therefore, it will correctly generate the code.

Note: The language can also be run with eclipse with "Run" -> "Eclipse Application", and creating an "Eketal Project", when doing this, it works, but the same file, built with Maven will crashed

Regards.

**Comment by LorenzoBettini** [comment]
You need to add a Dependency to the jbase runtime library when building with maven, that library defines the operators

**Comment by camilo040494** [comment]
I have tried the [jbase library](https://github.com/unicesi/eketal/blob/master/test/Hello-World/pom.xml#L125-L129) in the Example project, did you mean that library in that project or should the library be in the project that generates the DSL?

**Comment by LorenzoBettini** [comment]
I assumed that you're trying to compile your dsl files from maven Justin the xtext-maven-plugin, right? If so, you need to add that dep to the configuration of that maven plug-in. Otherwise I need to see some code to figure out what's going on.

**Comment by camilo040494** [comment]
-"I assumed that you're trying to compile your dsl files from maven Justin the xtext-maven-plugin, right?", exactly, i am trying that, also that dependency is in the configuration of that plugin as with the dependency of my language. ([pom](https://github.com/unicesi/eketal/blob/Log4/test/Hello-World/pom.xml#L125-L129))
```xml
<plugin>
	<groupId>org.eclipse.xtext</groupId>
		<artifactId>xtext-maven-plugin</artifactId>
		<version>${xtext-version}</version>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<languages>
				<language>
					<javaSupport>true</javaSupport>
					<setup>co.edu.icesi.eketal.EketalStandaloneSetupGenerated</setup>
					<outputConfigurations>
						<outputConfiguration>
							<outputDirectory>src/main/generated-sources/</outputDirectory>
						</outputConfiguration>
					</outputConfigurations>
				</language>
			</languages>
		</configuration>
		<dependencies>
			<dependency>
			    <groupId>net.sf.xtext-jbase</groupId>
			    <artifactId>jbase</artifactId>
			    <version>0.5.0</version>
			</dependency>
			<dependency>
				<groupId>co.edu.icesi.eketal</groupId>
				<artifactId>co.edu.icesi.eketal</artifactId>
				<version>1.0.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>co.edu.icesi.eketal</groupId>
				<artifactId>co.edu.icesi.eketal.lib</artifactId>
				<version>1.0.0-SNAPSHOT</version>
			</dependency>
		</dependencies>
</plugin>
```
I have compared it with other examples and it has everything.
If you need to see some other code of the project, all the project is [here](https://github.com/unicesi/eketal/tree/Log4), there are some examples in the "test" folder, and the "co.edu.icesi.eketal.parent-master" folder has the syntax and the grammar project.
The syntax of the project can be found [here](https://github.com/unicesi/eketal/blob/Log4/co.edu.icesi.eketal.parent-master/co.edu.icesi.eketal/src/co/edu/icesi/eketal/Eketal.xtext#L96-L98) and i suspect that those lines could have something to see.
Regards.

**Comment by camilo040494** [comment]
This error was due this 
```
<dependencies>
...
 <dependency>
  <groupId>org.eclipse.xtext</groupId>
  <artifactId>org.eclipse.xtext.xbase.lib</artifactId>
  <version>2.12.0</version>
 </dependency>
...
</dependencies>
```
 missing dependendy in the [pom](https://github.com/unicesi/eketal/blob/Log4/test/Hello-World/pom.xml)

**This is a dependency of the project, not the "xtext-maven-plugin" plugin**
